<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>LifeSupportAlarms</AssemblyName>
    <RootNamespace>LifeSupportAlarms</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugType>portable</DebugType>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>pdbonly</DebugType>
    <OutputPath>..\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\lib\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Core">
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\lib\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\lib\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="USILifeSupport">
      <HintPath>..\lib\USILifeSupport.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\lib\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CleanExtraOutputs" AfterTargets="Build">
    <ItemGroup>
      <ExtraFiles Include="$(OutputPath)*.pdb" />
      <ExtraFiles Include="$(OutputPath)*.nlp" />
      <ExtraFiles Include="$(OutputPath)mscorlib.dll" />
      <ExtraFiles Include="$(OutputPath)fr\**\*" />
    </ItemGroup>
    <Delete Files="@(ExtraFiles)" />
    <RemoveDir Directories="$(OutputPath)fr" ContinueOnError="true" />
  </Target>

</Project>
